---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "swift-migrator.fullname" . }}-multipart-migrator
  labels:
    app: {{ .Chart.Name }}
    environment: {{ .Values.environment }}
    version: {{ .Values.version }}
    git_commit: {{ .Values.git_commit }}
    git_tag: {{ .Values.git_tag }}
spec:
  replicas: {{ .Values.application.multipart.migrator.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      environment: {{ .Values.environment }}
  # This is the pod template
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        environment: {{ .Values.environment }}
        version: {{ .Values.version }}
        git_commit: {{ .Values.git_commit }}
    spec:
      containers:
        - name: {{ include "swift-migrator.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /opt/app-root/src/swift_migrator_subscriber.rb
          env:
            - name: TASK_UPLOAD_TYPE
              value: multipart
          envFrom:
            - secretRef:
                name: {{ include "swift-migrator.fullname" . }}-secret-environment
      imagePullSecrets:
        - name: {{ include "swift-migrator.fullname" . }}-pull
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "swift-migrator.fullname" . }}-part
  labels:
    app: {{ .Chart.Name }}
    environment: {{ .Values.environment }}
    version: {{ .Values.version }}
    git_commit: {{ .Values.git_commit }}
    git_tag: {{ .Values.git_tag }}
spec:
  replicas: {{ .Values.application.multipart.part.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      environment: {{ .Values.environment }}
  # This is the pod template
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        environment: {{ .Values.environment }}
        version: {{ .Values.version }}
        git_commit: {{ .Values.git_commit }}
    spec:
      containers:
        - name: {{ include "swift-migrator.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /opt/app-root/src/swift_part_subscriber.rb
          envFrom:
            - secretRef:
                name: {{ include "swift-migrator.fullname" . }}-secret-environment
      imagePullSecrets:
        - name: {{ include "swift-migrator.fullname" . }}-pull
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "swift-migrator.fullname" . }}-complete
  labels:
    app: {{ .Chart.Name }}
    environment: {{ .Values.environment }}
    version: {{ .Values.version }}
    git_commit: {{ .Values.git_commit }}
    git_tag: {{ .Values.git_tag }}
spec:
  replicas: {{ .Values.application.multipart.complete.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      environment: {{ .Values.environment }}
  # This is the pod template
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        environment: {{ .Values.environment }}
        version: {{ .Values.version }}
        git_commit: {{ .Values.git_commit }}
    spec:
      containers:
        - name: {{ include "swift-migrator.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /opt/app-root/src/swift_complete_subscriber.rb
          envFrom:
            - secretRef:
                name: {{ include "swift-migrator.fullname" . }}-secret-environment
      imagePullSecrets:
        - name: {{ include "swift-migrator.fullname" . }}-pull
