apiVersion: v1
kind: Secret
metadata:
  name: {{ include "swift-migrator.fullname" . }}-secret-environment
  labels:
    app: {{ .Chart.Name }}
    environment: {{ .Values.environment }}
type: Opaque
stringData:
  AMQP_URL: {{ .Values.amqp_url }}
  SWIFT_USER: {{ .Values.swift.user }}
  SWIFT_PASS: {{ .Values.swift.pass }}
  SWIFT_PROVIDER_URL_ROOT: {{ .Values.swift.provider_url_root }}
  SWIFT_PROVIDER_AUTH_URI: {{ .Values.swift.provider_auth_uri }}
  S3_USER: {{ .Values.s3.user }}
  S3_PASS: {{ .Values.s3.pass }}
  S3_PROVIDER_URL_ROOT: {{ .Values.s3.provider_url_root }}
  TASK_QUEUE_PREFIX: {{ .Values.task_queue_prefix }}
